# -*- coding: utf-8 -*-
"""Copy of Copy of day 1 assignment - lets upgrade

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Oe5_hFZFik7D4tOfdQLG3bMSsRv13LOx
"""

# it is very simple
# It is easily readable 
# No strictly syntax
# Dynamically Typed Language
"""
welocome to 
essential 2.0
"""

print("hello world")
print(""" hello letsupgrade""")

print("hello")
print("coders")

print("hello" , end ="  ")
print("coders" )

print("hello",  "coders")

a= 20;
print(type(a))

a= "hello"
print(type(a))

a="$"
print(type(a))

x= 10.25
print(type(x))

x= 10
y=20
z=30

x,y,z=10,20,30

a=b=c=20
print(a,b,c)

print(id(a))
print(id(b))
print(id(c))

a=b=c=20


print(id(a))
print(id(b))
print(id(c))

b=30
print(a,b,c) #immutablity

print(id(a), id(b), id(c))
print(type(id(a)))

b=20
print(id(a), id(b), id(c))

x=  input("Enter first  value: ")
y=  input("Enter second value: ")

print(type(x), type(y))

print(x + y)

x= input("Enter values:" )
print(x)
print(type(x))

"10,20,30,40"

x= int(input("enter values: "))
ptint(x)

x= input('enter values: ')
print(type(x))

val = [int(i)for i in x.split()]
print(val)

li =["hello", 35, 10, 25, "$"]
print(li)
print(type(li))

li = [12, 19,46,67,78]
li.sort()

print(li)

li.reverse()
print(li)

# slicing 

li= [12,25,10,5,1,3]
print(li[0:5]) #[start : end]

li = [int(i) for i in input("enter values: ").split()]

li=['10','20','30','40','50','0']
li.sort()

a=[10,20,30,40,50,34,12.57]
a.sort()
print("list after sorting is:",a)

a=[ 10,36,57,38,20,36]
a.reverse()
print(a)

a=[ 10, 45, 67, 89, 90, 9195]
a.reverse()
print("sorting a list in descending is",a)